### PR TITLE
Added deploy command for docker

### PR DESCRIPTION
**Pull request by lordozb**
afctl

### CODE REVIEW

**Comment by chattarajoy** [comment]
There's an official docker image of apache airflow on docker hub, can we try using that?

Also, a gif with demo?

**Comment by chattarajoy** [comment]
Let's create a contributing guide as well, would be easier for code reviewers as well to understand the code.

**Comment by chattarajoy** [comment]
Better start writing unit tests sooner, would be difficult to add them later and might need to restructure code to make it testable.

**Comment by lordozb** [comment]
> There's an official docker image of apache airflow on docker hub, can we try using that?
> 
> Also, a gif with demo?

This is just for testing purpose. @sunasra will be creating a docker-compose file that'll be actually used.
Yes, sure will attach a gif.

**Comment by lordozb** [comment]
> Let's create a contributing guide as well, would be easier for code reviewers as well to understand the code.

Will start creating it.

**Comment by lordozb** [comment]
> Better start writing unit tests sooner, would be difficult to add them later and might need to restructure code to make it testable.

Next few PRs will of tests. Will be setting up the pipeline now since this is blocked till git integration.

**Comment by lordozb** [comment]
@chattarajoy 
Deploy on Qubole via analyze coming soon.

**Comment by sunasra** [comment]
> There's an official docker image of apache airflow on docker hub, can we try using that?
> 
> Also, a gif with demo?

That docker image is used by airflow opensource team to run the test I guess. It also installs Hadoop and some other packages which doen't require to run airflow. I am referring https://hub.docker.com/r/apache/airflow
Let me know if any other official image is available.

**Pull request closed without merging**
